<script lang="ts">
  /**
   * QR + session code. The QR is generated by our own server
   * (/api/sessions/:code/qr.svg) — never a third-party QR service, since the
   * app has to work on a LAN with no internet.
   */
  let {
    code,
    size = 112,
    codeSize = 42,
    hero = false,
    joinHost = "",
  }: { code: string; size?: number; codeSize?: number; hero?: boolean; joinHost?: string } = $props();
</script>

<div class="join" class:hero>
  <div class="scan-target" style="--qr: {size}px">
    <img src="/api/sessions/{code}/qr.svg" alt="QR code to join session {code}" />
  </div>
  <div class="text-center">
    {#if joinHost}
      <p class="cap">Join at {joinHost}</p>
    {/if}
    <p class="code" style="font-size: {codeSize}px">{code}</p>
  </div>
</div>

<style>
  .join {
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 16px;
  }
  .join.hero {
    flex-direction: column;
    gap: 18px;
  }

  .scan-target {
    background: #fff;
    border-radius: 18px;
    padding: 10px;
    border: 4px solid var(--gold);
    box-shadow: 0 10px 28px rgba(0, 0, 0, 0.22);
  }
  .hero .scan-target {
    border-radius: 26px;
    padding: 20px;
    border-width: 6px;
    animation: pulseRing 2.2s ease-in-out infinite;
  }
  @keyframes pulseRing {
    0%, 100% { box-shadow: 0 0 0 0 rgba(255, 201, 60, 0.5); }
    50%      { box-shadow: 0 0 0 20px rgba(255, 201, 60, 0); }
  }
  .scan-target img {
    display: block;
    width: var(--qr);
    height: var(--qr);
  }

  .cap {
    font-weight: 900;
    letter-spacing: 0.14em;
    text-transform: uppercase;
    font-size: 15px;
    color: rgba(255, 255, 255, 0.82);
    margin: 0;
  }
  .hero .cap {
    font-size: 22px;
  }
  .code {
    font-weight: 900;
    letter-spacing: 0.08em;
    line-height: 1;
    margin: 6px 0 0;
    color: var(--white);
  }
  .hero .code {
    animation: pop 2.4s ease-in-out infinite;
  }
  @keyframes pop {
    0%, 100% { transform: scale(1); }
    50%      { transform: scale(1.03); }
  }
</style>
