#!/bin/bash
# =============================================================================
# scripturejam Install Script — Raspberry Pi / Debian
# https://github.com/darqlab/scripturejam
# Usage: curl -fsSL https://raw.githubusercontent.com/darqlab/scripturejam/main/scripts/install.sh | sudo bash
# =============================================================================

set -e

APP_NAME="scripturejam"
REPO="darqlab/scripturejam"
BRANCH="main"
INSTALL_DIR="/opt/yard/scripturejam"

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BOLD='\033[1m'
NC='\033[0m'

info()    { echo -e "${GREEN}[scripturejam]${NC} $1"; }
warning() { echo -e "${YELLOW}[Warning]${NC} $1"; }
error()   { echo -e "${RED}[Error]${NC} $1"; exit 1; }
step()    { echo -e "\n${BOLD}==> $1${NC}"; }

if [ "$EUID" -ne 0 ]; then
  error "Please run with sudo: curl -fsSL .../install.sh | sudo bash"
fi

APP_USER="${SUDO_USER:-pi}"

info "Starting scripturejam installation (user: ${APP_USER})..."

# -----------------------------------------------------------------------------
# 1. Docker
# -----------------------------------------------------------------------------
step "1. Docker"
if command -v docker &>/dev/null; then
  info "Docker already installed — $(docker --version | head -1)"
else
  info "Installing Docker..."
  apt-get install -y curl
  curl -fsSL https://get.docker.com | sh
  usermod -aG docker "${APP_USER}"
  info "Docker installed."
  warning "You may need to log out and back in for the docker group to take effect."
fi

if ! docker compose version &>/dev/null; then
  info "Installing Docker Compose plugin..."
  apt-get install -y docker-compose-plugin
fi

# -----------------------------------------------------------------------------
# 2. System dependencies
# -----------------------------------------------------------------------------
step "2. System dependencies"
apt-get update -qq
apt-get install -y git openssl python3 curl
info "System dependencies ready."

# -----------------------------------------------------------------------------
# 3. Clone or update repository
# -----------------------------------------------------------------------------
step "3. Repository"
if [ -d "${INSTALL_DIR}/.git" ]; then
  info "Existing installation found — updating..."
  sudo -u "${APP_USER}" git -C "${INSTALL_DIR}" pull origin "${BRANCH}"
else
  info "Cloning scripturejam repository..."
  mkdir -p "$(dirname "${INSTALL_DIR}")"
  sudo -u "${APP_USER}" git clone "https://github.com/${REPO}.git" "${INSTALL_DIR}"
fi
chown -R "${APP_USER}:${APP_USER}" "${INSTALL_DIR}"

# -----------------------------------------------------------------------------
# 4. Directory structure
# -----------------------------------------------------------------------------
step "4. Directory structure"
for dir in volumes/db volumes/redis secrets backups logs; do
  mkdir -p "${INSTALL_DIR}/${dir}"
done
chown -R "${APP_USER}:${APP_USER}" "${INSTALL_DIR}"
info "Directories ready."

# -----------------------------------------------------------------------------
# 5. Secrets — generate on first install only
# -----------------------------------------------------------------------------
step "5. Secrets"
POSTGRES_SECRET="${INSTALL_DIR}/secrets/postgres_password.txt"

if [ ! -f "${POSTGRES_SECRET}" ]; then
  info "Generating Postgres password..."
  openssl rand -hex 24 > "${POSTGRES_SECRET}"
  chmod 600 "${POSTGRES_SECRET}"
  chown root:root "${POSTGRES_SECRET}"
  info "Written: secrets/postgres_password.txt"
else
  info "Postgres secret already exists — skipping."
fi

ENV_FILE="${INSTALL_DIR}/.env"
if [ ! -f "${ENV_FILE}" ]; then
  info "Generating .env..."
  IP_HASH_SECRET=$(openssl rand -hex 32)
  PI_IP=$(hostname -I | awk '{print $1}')
  cat > "${ENV_FILE}" <<EOF
# scripturejam environment — generated by install.sh on $(date +%Y-%m-%d)

PUBLIC_URL=http://${PI_IP}:4000
PORT=3000
NODE_ENV=production

IP_HASH_SECRET=${IP_HASH_SECRET}

DATABASE_URL=postgresql://scripturejam:$(cat "${POSTGRES_SECRET}")@postgres:5432/scripturejam
REDIS_URL=redis://redis:6379

POSTGRES_USER=scripturejam
POSTGRES_DB=scripturejam
POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password

TZ=Asia/Manila
EOF
  chmod 640 "${ENV_FILE}"
  chown "${APP_USER}:${APP_USER}" "${ENV_FILE}"
  info "Written: .env"
  warning "Edit ${ENV_FILE} to set PUBLIC_URL and TZ for your region if needed."
else
  info ".env already exists — skipping (secrets preserved)."
fi

# -----------------------------------------------------------------------------
# 6. Docker Compose — generate on first install only
# -----------------------------------------------------------------------------
step "6. Docker Compose"
COMPOSE_FILE="${INSTALL_DIR}/docker-compose.yml"

if [ ! -f "${COMPOSE_FILE}" ]; then
  info "Writing docker-compose.yml..."
  cat > "${COMPOSE_FILE}" <<'YAML'
# scripturejam — Pi deployment
# Generated by install.sh — edit to customise ports or resources

secrets:
  postgres_password:
    file: ./secrets/postgres_password.txt

services:
  app:
    build:
      context: .
      dockerfile: app/server/Dockerfile
    image: scripturejam-app
    container_name: scripturejam-app
    restart: unless-stopped
    ports:
      - "4000:3000"
    env_file: .env
    environment:
      TZ: ${TZ:-Asia/Manila}
    secrets:
      - postgres_password
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:3000/healthz"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    logging:
      driver: json-file
      options: {max-size: "10m", max-file: "3"}

  postgres:
    image: postgres:16-alpine
    container_name: scripturejam-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-scripturejam}
      POSTGRES_DB: ${POSTGRES_DB:-scripturejam}
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      TZ: ${TZ:-Asia/Manila}
    secrets:
      - postgres_password
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-scripturejam}"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: json-file
      options: {max-size: "10m", max-file: "3"}

  redis:
    image: redis:7-alpine
    container_name: scripturejam-redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - ./volumes/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    logging:
      driver: json-file
      options: {max-size: "10m", max-file: "3"}
YAML
  chown "${APP_USER}:${APP_USER}" "${COMPOSE_FILE}"
  info "Written: docker-compose.yml"
else
  info "docker-compose.yml already exists — skipping."
fi

# -----------------------------------------------------------------------------
# 7. Helper scripts
# -----------------------------------------------------------------------------
step "7. Helper scripts"
SCRIPTS_DIR="${INSTALL_DIR}/scripts"

cat > "${SCRIPTS_DIR}/up.sh" <<'BASH'
#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."
docker compose up -d
echo "scripturejam stack is up."
BASH

cat > "${SCRIPTS_DIR}/down.sh" <<'BASH'
#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."
docker compose down
echo "scripturejam stack stopped."
BASH

cat > "${SCRIPTS_DIR}/deploy.sh" <<'BASH'
#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."
echo "Building scripturejam image..."
docker compose build app
echo "Restarting stack..."
docker compose up -d --remove-orphans
echo "Deploy complete."
docker compose ps
BASH

cat > "${SCRIPTS_DIR}/backup.sh" <<'BASH'
#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
BACKUP_FILE="backups/scripturejam_${TIMESTAMP}.sql.gz"
docker compose exec -T postgres pg_dump -U scripturejam scripturejam | gzip > "${BACKUP_FILE}"
echo "Backup written: ${BACKUP_FILE}"
ls -t backups/*.sql.gz 2>/dev/null | tail -n +15 | xargs -r rm --
echo "Old backups pruned (keeping last 14)."
BASH

chmod +x "${SCRIPTS_DIR}"/*.sh
chown "${APP_USER}:${APP_USER}" "${SCRIPTS_DIR}"/*.sh
info "Scripts ready: up.sh, down.sh, deploy.sh, backup.sh"

# -----------------------------------------------------------------------------
# 8. Bible texts (optional)
# -----------------------------------------------------------------------------
step "8. Bible texts"
BIBLE_DIR="${INSTALL_DIR}/content/bible"
if ls "${BIBLE_DIR}"/*.yaml &>/dev/null 2>&1; then
  info "Bible texts already installed — skipping."
else
  echo
  echo -e "  Verse text is shown after every answer — this is the core teaching moment."
  echo -e "  Installing requires: curl, python3, uv (~5 min, ~17 MB download)"
  echo
  read -r -p "  Install Bible texts now? (KJV, WEB, ASV) [y/N]: " INSTALL_BIBLE
  if [[ "${INSTALL_BIBLE:-n}" =~ ^[Yy]$ ]]; then
    if ! command -v uv &>/dev/null; then
      info "Installing uv..."
      sudo -u "${APP_USER}" curl -LsSf https://astral.sh/uv/install.sh | sudo -u "${APP_USER}" sh
      export PATH="$PATH:/home/${APP_USER}/.cargo/bin:/home/${APP_USER}/.local/bin"
    fi
    sudo -u "${APP_USER}" bash "${INSTALL_DIR}/content-tools/scripts/install-bible-texts.sh"
  else
    warning "Bible texts skipped — verse display will be unavailable."
    warning "Install later: bash ${INSTALL_DIR}/content-tools/scripts/install-bible-texts.sh"
  fi
fi

# -----------------------------------------------------------------------------
# 9. Build image
# -----------------------------------------------------------------------------
step "9. Build Docker image"
info "Building image (this may take several minutes on Pi)..."
cd "${INSTALL_DIR}"
sudo -u "${APP_USER}" docker compose build app
info "Image built."

# -----------------------------------------------------------------------------
# 10. Start stack
# -----------------------------------------------------------------------------
step "10. Start stack"
sudo -u "${APP_USER}" bash "${SCRIPTS_DIR}/up.sh"

info "Waiting for app to become healthy..."
READY=0
for i in $(seq 1 24); do
  if curl -sf "http://127.0.0.1:4000/healthz" &>/dev/null; then
    READY=1
    break
  fi
  sleep 5
done

# -----------------------------------------------------------------------------
# Done
# -----------------------------------------------------------------------------
PI_IP=$(hostname -I | awk '{print $1}')

echo ""
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}  scripturejam installed successfully!${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""
if [ "${READY}" -eq 1 ]; then
  echo -e "  Host console : ${YELLOW}http://${PI_IP}:4000/host${NC}"
  echo -e "  Players join : ${YELLOW}http://${PI_IP}:4000/j/<code>${NC}"
else
  echo -e "  ${YELLOW}App is still starting — check status with:${NC}"
  echo -e "    docker compose -f ${INSTALL_DIR}/docker-compose.yml ps"
  echo -e "    docker compose -f ${INSTALL_DIR}/docker-compose.yml logs -f app"
  echo ""
  echo -e "  Once healthy:"
  echo -e "  Host console : ${YELLOW}http://${PI_IP}:4000/host${NC}"
  echo -e "  Players join : ${YELLOW}http://${PI_IP}:4000/j/<code>${NC}"
fi
echo ""
echo -e "  Install dir  : ${INSTALL_DIR}"
echo -e "  Config       : ${INSTALL_DIR}/.env"
echo ""
echo -e "  Manage:"
echo -e "    ${INSTALL_DIR}/scripts/up.sh"
echo -e "    ${INSTALL_DIR}/scripts/down.sh"
echo -e "    ${INSTALL_DIR}/scripts/deploy.sh   # rebuild + restart"
echo -e "    ${INSTALL_DIR}/scripts/backup.sh   # pg_dump → backups/"
echo -e "    docker compose -f ${INSTALL_DIR}/docker-compose.yml logs -f"
echo ""
if [ "${READY}" -eq 0 ]; then
  warning "Bible texts were skipped. Run to enable verse display:"
  warning "  bash ${INSTALL_DIR}/content-tools/scripts/install-bible-texts.sh"
  warning "  Then rebuild: ${INSTALL_DIR}/scripts/deploy.sh"
fi
echo ""
